#include<bits/stdc++.h>

using namespace std;

int main()
{

   int t;
    cin>>t;
   for(int i=1;i<=t;i++)
    {
        string s;
        while(cin>>s) ///taking input strings when cin>>string is used endl is not considered as string ,usually when we give endl in
           /// this situation this endline will not be taken as input
        {
            cout<<s<<endl;


        }

    }





    return 0;
}
